/**
 * Metroidvania vertical-slice composer — a REAL genre pack (§5, §6, §21):
 * interconnected rooms, ability gates + backtracking, parry combat with
 * i-frames and knockback, boss with cinematic intro + phases, NPC dialogue
 * with choices, checkpoints, save slots, weather, parallax, gamepad.
 * Everything reads data/ files (§12) — the Change Engine edits data, not code.
 */
import type { GameSpec } from "../types";
import { godotIgnore, rootScene, iconSvg, hudScript } from "./gd_common";
import { sfxClick, sfxPickup, sfxHit } from "./gd_pro";
import { forgeDefaultSprites } from "../../assets/spriteForge";
import { deriveSpec, specToMarkdown, type GameSpecification } from "../../spec/gameSpec";
import { roomsJson } from "../../spec/roomGraph";
import { mvPlayerScript, mvCameraScript } from "../systems/mv_player";
import { mvEnemyScript, mvBossScript, mvNpcScript } from "../systems/mv_entities";
import { mvGameStateScript, mvMainScript, mvCheckpointScript, mvPickupScript } from "../systems/mv_world";
import { mvHudScript, mvMenuScript, mvMapScript } from "../systems/mv_ui";
import { WEB_EXPORT_PRESET } from "../godotExport";

export function metroidvaniaFiles(spec: GameSpec): Record<string, string | Uint8Array> {
  const pal = { accent: spec.palette.accent, bg: spec.palette.bg };
  const seed = spec.slug.split("").reduce((a, c) => a + c.charCodeAt(0), 7) * 13 + 101;
  const fullSpec: GameSpecification = deriveSpec({
    title: spec.title,
    genre: "action-adventure",
    dimension: "2.5d",
    flavor: "metroidvania",
    pillars: ["Responsive combat", "Interconnected exploration", "Ability-gated progression", "Melancholic atmosphere"],
    coreLoop: "Explore the ruined kingdom, fight wraiths, unlock the dash, open the Sovereign's Door and defeat the Hollow Sovereign.",
    idea: spec.shortDescription,
    seed,
  });

  const playerData = {
    speed: 260, jump: -420, gravity: 1150, parry_window: 0.22, parry_cd: 0.9,
    attack_cd: 0.38, attack_damage: 12, attack_range: 36, iframes: 0.8, dash_speed: 520, dash_cd: 0.8,
  };
  const enemiesData = {
    wraith: { hp: 30, speed: 130, damage: 8, telegraph: 0.45, range: 34, aggro: 260 },
    sentinel: { hp: 60, speed: 90, damage: 12, telegraph: 0.6, range: 40, aggro: 300 },
  };
  const bossesData = [
    { id: "sovereign", name: "The Hollow Sovereign", hp: 120, damage: 14, phases: 2 },
  ];
  const abilitiesData = { dash: { name: "Rift Dash", desc: "Um impulso curto que atravessa o espaço; abre caminhos selados." } };
  const dialogueData = {
    id: "keeper",
    start: "root",
    nodes: {
      root: {
        text: "Você acordou… de novo. Imortalidade é uma coroa pesada, criança.",
        choices: [
          { label: "Quem é você?", next: "who" },
          { label: "O que happened com este reino?", next: "kingdom" },
        ],
      },
      who: { text: "Eu guardava estas paredes quando ainda tinham Deus. Agora guardo só ecos.", next: "root" },
      kingdom: {
        text: "O Soberano Oco devorou a luz. A porta dele, ao leste, só se abre para quem dobra o espaço — busque a Galeria ao oeste.",
        next: "hint",
      },
      hint: { text: "Pare nas fogueiras para salvar sua alma. E quando o chefe surgir… aperte K no tempo certo." },
    },
  };

  const mvProjectGodot = `; Engine configuration file (generated by Nexus Forge)
config_version=5

[application]

config/name="${spec.title.replace(/"/g, "'")}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.3")

[autoload]

GameState="*res://scripts/core/game_state.gd"
GameMenu="*res://scripts/core/game_menu.gd"
HUD="*res://scripts/ui/hud.gd"
MapScreen="*res://scripts/core/map_screen.gd"

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

renderer/rendering_method="gl_compatibility"
`;

  return {
    "project.godot": mvProjectGodot,
    ".gitignore": godotIgnore(),
    "icon.svg": iconSvg(spec.palette.bg, spec.palette.accent),
    "export_presets.cfg": WEB_EXPORT_PRESET,

    // scenes — minimal roots, everything built in code (proven pattern)
    "scenes/main.tscn": rootScene("World", "Node", "res://scripts/world/main.gd"),
    "scenes/player.tscn": rootScene("Player", "CharacterBody2D", "res://scripts/player/player.gd"),
    "scenes/enemy.tscn": rootScene("Enemy", "CharacterBody2D", "res://scripts/ai/enemy.gd"),
    "scenes/boss.tscn": rootScene("Boss", "CharacterBody2D", "res://scripts/ai/boss.gd"),
    "scenes/npc.tscn": rootScene("Npc", "CharacterBody2D", "res://scripts/characters/npc.gd"),
    "scenes/checkpoint.tscn": rootScene("Checkpoint", "Area2D", "res://scripts/world/checkpoint.gd"),
    "scenes/ability_pickup.tscn": rootScene("Pickup", "Area2D", "res://scripts/world/ability_pickup.gd"),

    // scripts — SYSTEM LIBRARY (§11: coherent structure)
    "scripts/core/game_state.gd": mvGameStateScript(spec),
    "scripts/core/game_menu.gd": mvMenuScript(spec),
    "scripts/core/map_screen.gd": mvMapScript(),
    "scripts/player/player.gd": mvPlayerScript(spec),
    "scripts/player/camera_rig.gd": mvCameraScript(),
    "scripts/ai/enemy.gd": mvEnemyScript(),
    "scripts/ai/boss.gd": mvBossScript(spec),
    "scripts/characters/npc.gd": mvNpcScript(),
    "scripts/world/main.gd": mvMainScript(),
    "scripts/world/checkpoint.gd": mvCheckpointScript(),
    "scripts/world/ability_pickup.gd": mvPickupScript(),
    "scripts/ui/hud.gd": mvHudScript(spec),

    // DATA-DRIVEN DESIGN (§12) — Change Engine edits these, not code
    "data/spec.json": JSON.stringify(fullSpec, null, 2),
    "data/rooms.json": roomsJson(fullSpec),
    "data/player.json": JSON.stringify(playerData, null, 2),
    "data/enemies.json": JSON.stringify(enemiesData, null, 2),
    "data/bosses.json": JSON.stringify(bossesData, null, 2),
    "data/abilities.json": JSON.stringify(abilitiesData, null, 2),
    "data/dialogue.json": JSON.stringify(dialogueData, null, 2),

    // assets: sprites (animated) + audio (synth) + hud fallback
    ...Object.fromEntries(Object.entries(forgeDefaultSprites(pal))),
    "audio/pickup.wav": sfxPickup(),
    "audio/hit.wav": sfxHit(),
    "audio/click.wav": sfxClick(),
    "scripts/ui/hud_fallback.gd": hudScript(spec),

    // docs
    "docs/game-specification.md": specToMarkdown(fullSpec),
    "docs/README.md": `# ${spec.title}\n\n${spec.shortDescription}\n\n## Controles\n- Mover: WASD/setas · Saltar: ESPAÇO · Atacar: J/X · **Parry: K/C** · Dash: L/Z (após desbloquear)\n- Interagir: E · Mapa: TAB · Pausa: ESC\n- **Gamepad suportado** (analógico move; A/B/X/Y mapeados)\n\n## O loop do slice\nExplore o Claustro → fale com o Guardião → atravesse a Galeria (oeste) → pegue o DASH →\nabra a Capela (leste) → ative a fogueira → enfrente **O Soberano Oco** (parry no tempo certo!).\n\n## Sistemas\nFSM de inimigos, parry com stagger, i-frames, knockback, checkpoints com save versionado,\ndiálogo com escolhas, mapa por descoberta, chuva + parallax 2.5D, chefe com fases e intro cinematográfica.\n`,
  };
}
