/**
 * Genre archetype knowledge base.
 *
 * Distilled from the user's reference list (RimWorld, Dying Light, Spider-Man 2,
 * Hogwarts Legacy, Genshin, ZZZ, Hollow Knight, Celeste, Hades, Diablo, ETS2,
 * R.E.P.O., Rucoy, and ~110 others). These are ABSTRACT design patterns —
 * core loops, system decompositions, MVP slices and known pitfalls.
 * They contain NO copyrighted content, assets or code: patterns only.
 * The Director injects relevant archetypes to ground planning; templates
 * use them to drive deterministic (offline) project generation.
 */

export interface GenreArchetype {
  id: string;
  label: string;
  examples: string[];
  dimension: "2d" | "3d" | "2.5d";
  coreLoop: string;
  pillars: string[];
  keySystems: string[];
  mvpSlice: string[];
  pitfalls: string[];
  engineFit: { godot4: number; unreal5: number }; // 0..1 suitability
  /** §5 mission: complete configurability profile (progressive enrichment —
   *  new archetypes ship with it; older ones gain it over time). */
  config?: {
    camera: string;
    controls: string;
    progression: string;
    content: string;
    ui: string;
    audio: string;
    animation: string;
    save: string;
    performance: string;
    testing: string;
    platforms: string[];
  };
}

export const GENRE_ARCHETYPES: GenreArchetype[] = [
  {
    id: "colony-survival",
    label: "Colony Survival / City Builder",
    examples: ["RimWorld", "Farthest Frontier", "Necesse", "Oxygen Not Included", "NeoHaven-style"],
    dimension: "2.5d",
    coreLoop: "Land settlers -> gather resources -> build shelter -> satisfy needs (food/sleep/safety) -> assign jobs -> survive threats (weather/raids) -> grow population -> research tech -> expand territory.",
    pillars: ["Emergent story from simulation", "Needs & mood systems", "Base building as expression", "Escalating threat curve"],
    keySystems: ["colonist needs (hunger/sleep/joy)", "job assignment & priorities", "construction grid", "resource stockpiles", "food & farming", "raids/events", "research tree", "seasons & weather", "pathfinding", "save/load"],
    mvpSlice: ["tile-based world", "place walls/beds/farm plots", "3 colonists with needs draining", "harvest wood/berries", "day/night cycle", "one threat event", "win/lose conditions"],
    pitfalls: ["pathfinding bugs in closed doors", "needs starvation spirals (hard fun-killer)", "save corruption", "UI overload before depth"],
    engineFit: { godot4: 0.9, unreal5: 0.55 },
     config: {
      camera: "Angled top/isometric with zoom bands; follow-colonist inspect cam",
      controls: "Mouse: select/order/build/zone; hotbars; WASD pan",
      progression: "Tech tree + population milestones; threat curve by season",
      content: "Seeded maps, raid compositions, event tables, biome zones",
      ui: "Needs panel, resource readout, work priorities, alerts feed",
      audio: "Ambient biomes, alert stingers, calm base loop",
      animation: "Pawn locomotion 8-dir + carrying states; simple prop states",
      save: "Full-colony serialization, multiple slots, autosave",
      performance: "Pathfinding budgets; hundreds of pawns; chunked tick",
      testing: "Needs/spiral sims, pathfinding stress, save roundtrip, raid soak",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "survival-craft",
    label: "Survival & Crafting",
    examples: ["Rust", "DayZ", "Project Zomboid", "7 Days to Die", "Don't Starve", "Sons of the Forest", "Raft", "Palworld"],
    dimension: "3d",
    coreLoop: "Spawn with nothing -> scavenge -> craft tools -> build shelter -> manage hunger/thirst/temperature -> fight or flee fauna/enemies -> tech up -> secure a home.",
    pillars: ["Scarcity pressure", "Meaningful crafting tree", "Territory & safety", "Risk gradient day vs night"],
    keySystems: ["vitals (hunger/thirst/warmth)", "item crafting recipes", "resource nodes & respawn", "durability", "enemy AI aggression states", "base building (snap grids)", "inventory & hotbar", "day/night", "map generation"],
    mvpSlice: ["island/terrain", "punch trees / pick stones", "campfire + cooked food", "hunger + health", "one hostile at night", "crafting menu", "backpack"],
    pitfalls: ["inventory UX death", "empty-world syndrome", "grind without goals", "multiplayer sync (defer MP)"],
    engineFit: { godot4: 0.75, unreal5: 0.9 },
     config: {
      camera: "First or third person, free look; head-bob for feedback",
      controls: "WASD + mouse look; inventory hotbar; radial craft",
      progression: "Crafting tiers gated by resources and stations",
      content: "Resource maps, wildlife tables, POIs, day/night raids",
      ui: "Inventory grid + drag, crafting tree, vitals bars",
      audio: "Diegetic gather sounds, night dread layer, wildlife calls",
      animation: "First-person tool swings; third-person loco sets",
      save: "World + inventory chunks, respawn persistence",
      performance: "Streaming chunks; 60fps on mid GPU",
      testing: "Craft-graph consistency, hunger curves, death/respawn loops",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "open-world-action",
    label: "Open-World Action Adventure",
    examples: ["Spider-Man 2", "Hogwarts Legacy", "Batman Arkham Knight", "Ghost of Tsushima", "God of War", "RDR2", "Horizon", "Far Cry", "Days Gone", "Assassin's Creed series", "Where Winds Meet", "Crimson Desert"],
    dimension: "3d",
    coreLoop: "Explore district -> find activity (camp/collection/mystery) -> combat or stealth encounter -> rewards (gear/XP/lore) -> traversal to next landmark -> story beats unlock regions.",
    pillars: ["Traversal is fun", "Readable combat with depth", "Landmark-driven exploration", "Power fantasy growth"],
    keySystems: ["third-person controller (camera, lock-on)", "melee/ranged combat (hitboxes, combos, dodge)", "enemy AI (squad behaviors, aggro)", "quest system (main/side)", "open-world streaming (chunks)", "loot & upgrades", "dialogue/cinematics", "map & fast travel", "minimap/waypoints"],
    mvpSlice: ["1 km2 island", "third-person movement (run/jump/climb)", "1 weapon light+heavy+dash", "3 enemy types with basic AI", "1 quest chain", "XP + level ups", "day cycle"],
    pitfalls: ["empty open world", "camera fighting the player", "quest flag state hell", "scope explosion - prototype ONE loop first"],
    engineFit: { godot4: 0.6, unreal5: 1.0 },
     config: {
      camera: "Third person follow with collision-aware boom; photo mode later",
      controls: "Character action: light/heavy/jump/dodge; contextual prompts",
      progression: "Region unlocks, gear tiers, main+side quest chains",
      content: "Hand-authored POIs on procedural regions, faction camps",
      ui: "Minimal HUD, compass strip, quest log, diegetic markers",
      audio: "Layered explore/combat by region; radio-style diegetic tracks",
      animation: "Loco sets 8-dir, combat blends, finisher cinematics",
      save: "Checkpoint + world-state persistence",
      performance: "LOD terrain, crowd budgets, streaming",
      testing: "Quest-flag graphs, traversal reachability, combat balance soak",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "soulslike",
    label: "Souls-like Action RPG",
    examples: ["Dark Souls", "Lies of P", "Remnant 2", "Blasphemous (2D take)", "Hades (roguelite take)"],
    dimension: "3d",
    coreLoop: "Enter zone -> learn enemy patterns -> collect souls -> die -> respawn at bonfire -> spend souls -> push deeper -> unlock shortcut -> boss -> repeat.",
    pillars: ["Punishing but fair", "Bonfire checkpoint economy", "Bosses as exams", "Atmosphere over exposition"],
    keySystems: ["stamina combat (light/heavy/dodge/parry)", "poise & stagger", "bonfire checkpoints", "soul currency + level-up stats", "weapon movesets", "boss patterns/phases", "shortcut world design", "invaders/summons (defer MP)"],
    mvpSlice: ["3 interconnected rooms", "stamina system", "light/heavy/dodge", "2 enemy types with telegraphs", "1 bonfire", "1 boss with 2 phases", "souls + stats"],
    pitfalls: ["unfair hitboxes destroy trust", "input buffering issues", "boss too complex for MVP"],
    engineFit: { godot4: 0.7, unreal5: 1.0 },
     config: {
      camera: "Locked third-person orbit with soft auto-face in combat",
      controls: "Commit-based attacks, dodge-roll i-frames, parry windows; gamepad first",
      progression: "Interconnected shortcuts, boss gates, build variety",
      content: "Authored encounter layouts; bonfire-equivalent pacing anchors",
      ui: "Diegetic menus, stamina/hearts bars, minimal prompts",
      audio: "Silence-driven dread, boss leitmotifs, hit weight foley",
      animation: "Anticipation-heavy attack sets, stagger reactions",
      save: "Checkpoint slots at rest points only",
      performance: "Stable 60 in boss arenas; hitbox precision over VFX",
      testing: "I-frame tables, boss pattern scripts, hit-regression",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "metroidvania",
    label: "Metroidvania",
    examples: ["Hollow Knight", "Rain World", "Dead Cells (roguelite hybrid)", "Blasphemous"],
    dimension: "2d",
    coreLoop: "Explore interconnected map -> hit ability wall -> backtrack with new ability -> unlock region -> find boss/gateway -> repeat.",
    pillars: ["Interconnected map with shortcuts", "Ability-gated progression", "Atmospheric solitude", "Tight combat & movement"],
    keySystems: ["room-based level map", "ability unlocks (double-jump/dash/wall-climb)", "map & cartographer", "bench checkpoints", "enemy bestiary", "charm/relic builds", "secret walls"],
    mvpSlice: ["12-room handcrafted map", "tight platformer controller", "1 melee attack + dash unlock", "2 enemies", "1 mini-boss", "bench save", "map screen"],
    pitfalls: ["ability gating unclear", "backtracking without fast-travel tedium", "floaty controls"],
    engineFit: { godot4: 1.0, unreal5: 0.3 },
     config: {
      camera: "2D follow with look-ahead and room limits; map overlay",
      controls: "Run/jump/attack/dash, ability-gated traversal; gamepad first",
      progression: "Ability gates + backtracking; map completion percent",
      content: "Room graph with shortcuts, secrets, biome zones",
      ui: "Room map, hearts, ability prompts, boss bar",
      audio: "Biome loops + boss theme; sting on unlock",
      animation: "State anims with anticipation/impact frames",
      save: "Checkpoints + slot versions",
      performance: "Room-streamed 2D; trivial GPU, logic-heavy",
      testing: "Level solvability (gates↔pickups), reachability, QA probes",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
  {
    id: "precision-platformer",
    label: "Precision Platformer",
    examples: ["Celeste", "Cuphead (run-and-gun hybrid)", "Super Meat Boy lineage"],
    dimension: "2d",
    coreLoop: "Attempt screen -> die -> learn spacing -> clear -> chase strawberries/B-sides -> assist options widen audience.",
    pillars: ["Pixel-perfect controls", "Death is cheap & instant restart", "Screen-sized challenges", "Assist accessibility"],
    keySystems: ["coyote time + jump buffering", "dash/wall mechanics", "screen restart < 0.5s", "collectibles", "chapter select", "assist mode", "leaderboards"],
    mvpSlice: ["30-tile physics (coyote/buffer)", "walk/jump/dash/climb", "spikes + moving platforms", "3 chapters x 6 screens", "deaths counter", "instant respawn"],
    pitfalls: ["input latency kills it", "unclear hazards", "frustration without assist"],
    engineFit: { godot4: 1.0, unreal5: 0.1 },
     config: {
      camera: "Locked-follow with input-neutral framing (no drift)",
      controls: "Tight coyote/buffer jump; run toggle; zero input lag priority",
      progression: "Chapter difficulty curve; collectible optional routes",
      content: "Hand-crafted screens with golden-path rigor",
      ui: "Deaths counter, timer, chapter select",
      audio: "Beat-sync option; clean SFX for every mechanic",
      animation: "Squash/stretch jumps, death FX, hair/cloth secondary",
      save: "Chapter progress + best times",
      performance: "Deterministic physics at fixed tick",
      testing: "Frame-perfect jump tables, input-buffer regressions",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
  {
    id: "cozy-life-sim",
    label: "Cozy Life/Farm Sim",
    examples: ["Stardew Valley", "Graveyard Keeper", "Dave the Diver", "Moonlighter", "Sky: Children of the Light"],
    dimension: "2d",
    coreLoop: "Daily routine (farm/dive/shop) -> seasonal cycles -> relationships & town events -> economic upgrades -> cozy expansion.",
    pillars: ["Ritual & routine comfort", "Seasonal content variety", "Relationship warmth", "No-fail pacing"],
    keySystems: ["clock & seasons", "crop growth & watering", "tool stamina", "NPC schedules & gifts", "friendship events", "shop economy", "crafting", "fishing/minigames"],
    mvpSlice: ["64x64 farm", "4 crops & seasons", "day clock + sleep", "1 NPC with gifts", "shipping bin economy", "watering can", "energy bar"],
    pitfalls: ["energy punishing too early", "content gates by season blocking", "inventory friction"],
    engineFit: { godot4: 1.0, unreal5: 0.25 },
     config: {
      camera: "Angled top; gentle follow; zoom for decorating",
      controls: "Mouse-driven: move, interact, inventory, tool select",
      progression: "Seasons, relationship arcs, farm/gear upgrades",
      content: "Villagers with schedules, festival calendar, crop tables",
      ui: "Calendar, relationship meters, toolbars, letters inbox",
      audio: "Seasonal acoustic loops, rain/storm moods",
      animation: "Crop growth stages, villager daily emotes",
      save: "Daily autosave with rollback slots",
      performance: "Calm budgets; schedule tick optimization",
      testing: "Schedule sim, seasonal crop tables, save roundtrip",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
  {
    id: "anime-action",
    label: "Anime Action RPG (Gacha-style)",
    examples: ["Genshin Impact", "Zenless Zone Zero", "Wuthering Waves lineage"],
    dimension: "3d",
    coreLoop: "Team of 3 swap combos -> elemental reactions -> open-world puzzles -> character gacha -> ascend gear -> abyss/rogue events.",
    pillars: ["Swappable team combat", "Elemental reaction depth", "Anime polish & style", "Session-based events"],
    keySystems: ["3-character swap combat", "elemental reaction matrix", "stamina (sprint/glide)", "open-world puzzles", "wish/gacha economy", "artifact/relic stats", "event scheduling", "co-op"],
    mvpSlice: ["1 arena + 3 playable heroes", "swap combo + 1 elemental reaction", "light attack chain", "1 boss", "wish screen (with local currency)"],
    pitfalls: ["balancing gacha vs fairness", "element matrix combinatorial bugs", "style ceiling high without VFX budget"],
    engineFit: { godot4: 0.65, unreal5: 0.95 },
     config: {
      camera: "Third-person lock-on with cinematic skill zooms",
      controls: "Combo strings + dodge + skill rotations; gamepad first",
      progression: "Character/gear gacha-lite; level bands",
      content: "Encounter arenas, event stages, boss raids",
      ui: "Party frames, skill bar, combo counter, banner screens",
      audio: "Vocal battle themes, element SFX layers",
      animation: "Combo chains with cancels; skill cut-in flashes",
      save: "Account-local slots; team loadouts",
      performance: "VFX budget discipline; 60 in arenas",
      testing: "Combo state machines, elemental counter tables, drop rates",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "arpg-loot",
    label: "Action RPG / Loot Grinder",
    examples: ["Diablo series", "Last Epoch", "Hades", "Minecraft Dungeons", "Hero Siege", "Cult of the Lamb (colony hybrid)"],
    dimension: "2.5d",
    coreLoop: "Clear zone -> loot drops -> build crafting (skills/gear) -> tougher zone -> boss -> ascend tiers.",
    pillars: ["Loot dopamine", "Build expression", "Readable power curve", "Endgame loop"],
    keySystems: ["affix/rarity itemization", "skill tree", "procedural zones", "elites & bosses", "stash & inventory", "difficulty tiers", "status effects", "gold economy"],
    mvpSlice: ["1 procedural dungeon floor", "4 skills", "rarity loot with 2 affixes", "1 boss", "town hub with stash/merchant", "harder NG+ tier"],
    pitfalls: ["drop rates economic suicide", "skill synergies OP on day 1", "inventory full 24/7"],
    engineFit: { godot4: 0.9, unreal5: 0.7 },
     config: {
      camera: "Angled top follow with cursor-aim",
      controls: "Click-stick movement + skill bar; build-defining keybinds",
      progression: "Gear tiers, affix rolls, difficulty tiers",
      content: "Dungeon tilesets, elite packs, loot tables",
      ui: "Inventory grid with tooltip compare, skill tree, loot feed",
      audio: "Loop intensity by zone; loot stingers by rarity",
      animation: "Skill VFX sets; class-specific attack anims",
      save: "Character slots + stash persistence",
      performance: "Mob-density scaling; loot-drop pooling",
      testing: "Affix roll sanity, drop-rate sims, skill regression",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "fps-multiplayer",
    label: "FPS / Military Multiplayer",
    examples: ["COD: Warzone", "Battlefield 2042", "Hell Let Loose", "World War Z (co-op)", "Dead Island", "Dying Light (parkour hybrid)"],
    dimension: "3d",
    coreLoop: "Squad up -> objective/zombies -> gunplay rounds -> unlocks -> next round.",
    pillars: ["Gunfeel first", "Objective design", "Squad interdependence", "Netcode fairness"],
    keySystems: ["hitscan/projectile shooting", "recoil & TTK", "loadouts", "objective modes", "netcode (rollback/anticheat later)", "AI hordes", "scoreboard"],
    mvpSlice: ["1 arena map", "1 rifle full recoil curve", "aim & hit markers", "target dummies + 1 bot", "deathmatch score", "killfeed"],
    pitfalls: ["netcode underestimated", "TTK tuning rage", "MVP: build gunfeel sandbox first"],
    engineFit: { godot4: 0.6, unreal5: 1.0 },
     config: {
      camera: "First person; ADS transitions; death cam",
      controls: "Mouse+keyboard standard; sensitivity presets",
      progression: "Match progression + seasonal cosmetics (no power creep)",
      content: "Arena maps with lane/sightline rigor; modes",
      ui: "Crosshair, kill feed, scoreboard, minimal in-match",
      audio: "Spatial footsteps/weapons; team comms mix",
      animation: "Weapon sets, hit confirms, vault",
      save: "Profile/settings only; matches ephemeral",
      performance: "Tick-rate stability; 120fps target on mid GPU",
      testing: "Netcode rollback/snapshot, hit-reg, 8-player soak",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "session-horror",
    label: "Co-op Session Horror",
    examples: ["R.E.P.O.", "Hellmart", "Escape the Backrooms", "Lethal Company lineage", "Miside", "Backrooms"],
    dimension: "3d",
    coreLoop: "Drop into run-down zone -> scavenge quota loot -> physics-y co-op chaos -> entity hunts you -> extract or die -> sell -> buy gear -> scarier zone.",
    pillars: ["Physics co-op comedy", "Dread escalation", "Quota economy", "Proximity voice moments"],
    keySystems: ["physics grab & carry", "procedural level tiles", "monster AI with senses", "quota & shop", "proximity audio", "extraction", "permadeath per run"],
    mvpSlice: ["1 tiled level", "physics pickup & drop", "1 monster (patrol -> chase)", "quota of 6 items", "shop between rounds", "2-player local co-op"],
    pitfalls: ["monster AI stuck", "physics jank funny once then annoying", "netcode for physics"],
    engineFit: { godot4: 0.75, unreal5: 0.85 },
     config: {
      camera: "First person with flashlight cone emphasis",
      controls: "Grab/crouch/sprint; voice-proximity focus",
      progression: "Run-based quota/economy meta (co-op loop)",
      content: "Seeded facility layouts; monster behavior tables",
      ui: "Scanner/radar readout, quota tracker, minimal HUD",
      audio: "Proximity voice as core mechanic; silence+stingers",
      animation: "Monster telegraphs; ragdoll pickups",
      save: "Meta quota/credits between runs",
      performance: "Dark-scene lighting budgets; headroom for monsters",
      testing: "Spawn fairness, monster pathing, quota econ balance",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "psychological-horror",
    label: "Atmospheric / Psychological Horror",
    examples: ["Silent Hill F", "Mimesis", "Detroit: Become Human (narrative)", "Stray (atmosphere adventure)"],
    dimension: "3d",
    coreLoop: "Explore unsettling space -> environmental storytelling -> chase/hide setpieces -> narrative branches -> endings.",
    pillars: ["Dread over jump scares", "Sound design leads", "Narrative weight", "Safe rooms contrast"],
    keySystems: ["tension director (audio/creature staging)", "hide & seek AI", "dialogue/branch states", "puzzle scenes", "endings tracker"],
    mvpSlice: ["1 apartment block", "flashlight + notes", "1 stalking entity", "2 puzzles", "3 endings from choices", "ambient audio bed"],
    pitfalls: ["repeated deaths kill fear", "over-dark unreadable scenes", "branch logic bugs"],
    engineFit: { godot4: 0.7, unreal5: 0.9 },
     config: {
      camera: "Fixed/authored angles + slow dolly; no player-control cam",
      controls: "Walk/interact/inspect only (deliberate powerlessness)",
      progression: "Narrative gate progression; sanity shifts",
      content: "Authored spaces with meaning-dense props",
      ui: "Diegetic notes/inventory; zero gamey HUD",
      audio: "Binaeral beds, diegetic sources, silence design",
      animation: "Subtle NPC idles; object glances",
      save: "Chapter checkpoints",
      performance: "Stable frame pacing for tension",
      testing: "Story-flag graphs, trigger maps, subtitle integrity",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "rts",
    label: "Real-Time Strategy",
    examples: ["Age of Empires", "Age of Mythology"],
    dimension: "2.5d",
    coreLoop: "Gather -> build base -> tech up -> army production -> map control -> decisive battle.",
    pillars: ["Economic decisions under pressure", "Counter-unit depth", "Map vision warfare", "Macro/micro balance"],
    keySystems: ["resource gatherers", "production queues", "unit counters & fog of war", "formation & control groups", "tech ages", "AI opponent (scripted then search)"],
    mvpSlice: ["1 map", "3 resource nodes", "5 units + 3 buildings", "drag-select + commands", "1 scripted enemy wave", "win by destroying HQ"],
    pitfalls: ["pathfinding traffic jams", "AI cheating accusations", "UI click overload"],
    engineFit: { godot4: 0.8, unreal5: 0.5 },
     config: {
      camera: "Free-pan strategy camera with edge scroll + hotkey jumps",
      controls: "Box-select, control groups, production hotkeys",
      progression: "Eco→tech→army curve; map objectives",
      content: "Symmetric/terrain maps, unit rosters, AI generals",
      ui: "Selection panel, build queues, minimap, control groups",
      audio: "Faction stingers, unit confirmations",
      animation: "Unit 8-dir loco, death anims, weapon fire",
      save: "Match replays + campaign slots",
      performance: "Pathfinding for 200+ units; sim determinism",
      testing: "Build-tree consistency, pathfinding stress, AI scrim",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "racing-sim",
    label: "Racing / Driving",
    examples: ["Forza Horizon", "Need for Speed (Unbound)", "Euro Truck Simulator 2", "American Truck Simulator", "Rocket League (sport hybrid)"],
    dimension: "3d",
    coreLoop: "Pick route/car -> drive loop -> earn currency -> upgrade/tune -> harder events -> livery expression.",
    pillars: ["Handling feel", "Route variety", "Progression garage", "Sound of speed"],
    keySystems: ["vehicle physics (suspension/grip)", "AI traffic/racers", "event & race modes", "career progression", "livery editor", "cops/patrol (NFS)", "cargo & trailer physics (truck sim)"],
    mvpSlice: ["1 circuit + 1 car", "arcade handling model", "3 AI racers on spline", "lap timing", "1 upgrade (tires)"],
    pitfalls: ["physics jello cars", "AI rubber-banding rage", "track collision seams"],
    engineFit: { godot4: 0.7, unreal5: 0.95 },
     config: {
      camera: "Cockpit/chase/hood with speed FOV response",
      controls: "Wheel/gamepad analog priority; assists tiers",
      progression: "Car class unlocks, lap-time mastery",
      content: "Track rosters with surface types, weather presets",
      ui: "Speedo/telemetry overlay, standings, minimap",
      audio: "Engine RPM layers, tire/brake foley, countdown",
      animation: "Suspension body-roll; wheel physics visual",
      save: "Car setups, championships, best laps",
      performance: "Physics tick 240-360hz; stable frame pacing",
      testing: "Lap validity, physics determinism, ghost replay parity",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "physics-coop",
    label: "Physics Party / Puzzle",
    examples: ["Poly Bridge", "Golf With Your Friends", "Party Machine", "Fall Guys lineage"],
    dimension: "3d",
    coreLoop: "Present puzzle/course -> attempt with physics -> fail hilariously -> retry -> next round with friends.",
    pillars: ["Emergent comedy", "Readable physics", "Quick rounds", "Spectatorability"],
    keySystems: ["rigidbody physics", "constraints (rope/bridge)", "win conditions & courses", "local co-op hotseat", "level editor (later)", "turn timers"],
    mvpSlice: ["3 bridge puzzles", "stress simulation", "budget system", "pass/fail with collapse", "replay ghost"],
    pitfalls: ["physics determinism across machines", "difficulty wall", "content throughput"],
    engineFit: { godot4: 0.8, unreal5: 0.7 },
     config: {
      camera: "Dynamic framed ensemble (keeps all players in view)",
      controls: "Grab/throw/climb; simple verb economy",
      progression: "Puzzle arc; optional time/score play",
      content: "Puzzle rooms with physics verbs; sandbox toys",
      ui: "Objective banner, emote wheel, minimal HUD",
      audio: "Goofy foley layers, session ambience",
      animation: "Ragdoll comedy; floppy-prop secondary",
      save: "Level progress per party",
      performance: "Solver stability with stacked bodies",
      testing: "Puzzle solvability, solver stress, respawn logic",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "pixel-mmorpg",
    label: "2D Pixel MMORPG (Mobile)",
    examples: ["Rucoy Online", "Tibia-likes", "Old-school mobile MMOs"],
    dimension: "2d",
    coreLoop: "Grind mobs -> loot & levels -> party dungeons -> PvP zones -> trade economy -> guild wars.",
    pillars: ["Grind with payoff", "Social pressure/alliances", "Economy as endgame", "Low-end device reach"],
    keySystems: ["tile movement & combat", "XP/skill progression", "loot & trading", "chat & parties", "guild system", "server persistence", "mobile touch UI"],
    mvpSlice: ["1 overworld map", "melee combat", "5 monsters with respawns", "inventory & equipment", "local chat", "save persistence"],
    pitfalls: ["server architecture early", "economy dupes/exploits", "content treadmill"],
    engineFit: { godot4: 0.9, unreal5: 0.2 },
     config: {
      camera: "Tile-follow 2D with smooth zoom bands",
      controls: "Click/WASD hybrid; action bar 1-0; mobile touch parity",
      progression: "Level bands, gear tiers, daily quests",
      content: "Zone maps, spawn tables, quest chains",
      ui: "Chat, party frames, minimap, mobile-first bars",
      audio: "Zone loops; combat SFX spam discipline",
      animation: "Directional sprite sets; equipment layers",
      save: "Server-authoritative (needs backend)",
      performance: "Net tick 10-20hz; client prediction",
      testing: "Latency sims, spawn economy, mobile perf profiles",
      platforms: ["windows", "linux", "android", "ios"],
    },
  },
  {
    id: "jrpg-narrative",
    label: "Turn-based / Narrative RPG",
    examples: ["Clair Obscur: Expedition 33", "Sea of Stars", "Baldur's Gate 3", "Detroit: Become Human"],
    dimension: "3d",
    coreLoop: "Story beat -> party management -> tactical turn combat -> explore -> next narrative act.",
    pillars: ["Combat as puzzle", "Party synergy depth", "Story choices matter", "Rhythm & timing flair"],
    keySystems: ["turn order & action economy", "elements/status matrix", "party builds", "branching narrative states", "exploration encounters", "save slots"],
    mvpSlice: ["3 characters with 3 skills", "turn battle vs 3 enemy types", "weakness system", "2 story choices with outcomes", "1 boss"],
    pitfalls: ["choice consequences unsatisfying", "combat pacing drag", "null builds"],
    engineFit: { godot4: 0.8, unreal5: 0.8 },
     config: {
      camera: "Authored scene angles; battle tableau; no free cam",
      controls: "Menu-driven: confirm/cancel/page; gamepad parity",
      progression: "Chapter acts, party growth, side arcs",
      content: "Authored scenes, encounter tables, dialogue trees",
      ui: "Dialogue box with portraits, battle menus, quest log",
      audio: "Leitmotif scoring per character/region",
      animation: "Battle pose sets, emote portraits, VFX spells",
      save: "Chapter slots + autosave",
      performance: "Trivial; asset streaming for scenes",
      testing: "Flag-graph completeness, encounter balance, choice integrity",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
  {
    id: "zombie-openworld",
    label: "Zombie Parkour Open-World (Dying Light-style)",
    examples: ["Dying Light 1 & 2", "Dead Island", "World War Z"],
    dimension: "3d",
    coreLoop: "Day: scavenge & quests -> night: hunter becomes hunted -> parkour escape/combat -> safe house -> skill trees -> territory",
    pillars: ["Parkour flow", "Day/night risk inversion", "Melee brutality", "Progression hooks"],
    keySystems: ["parkour movement (climb/vault/grapple)", "melee weapons & durability", "night volatility/volatiles", "safe zones & sleep", "quests & reputation", "co-op drop-in (later)"],
    mvpSlice: ["1 district rooftops", "parkour moves", "1 melee weapon tree", "day/night with faster night zombies", "1 safehouse quest", "skill XP"],
    pitfalls: ["parkour getting stuck on geometry", "night too punishing early", "combat vs flow balance"],
    engineFit: { godot4: 0.55, unreal5: 1.0 },
     config: {
      camera: "First-person with parker momentum feel",
      controls: "Run/climb/vault/combat; stamina discipline",
      progression: "Day/night cycle arcs; safehouse economy",
      content: "District maps, horde triggers, loot economy",
      ui: "Compass minimalism, stamina, infection cues",
      audio: "Night horde dread layers; heartbeat systems",
      animation: "Parker vault/climb sets; horde crowd anims",
      save: "District checkpoints; permadeath options",
      performance: "Crowd LOD for hordes; streaming city",
      testing: "Parkler reachability, horde spawn fairness, night economy",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "sandbox-voxel",
    label: "Voxel / Sandbox Adventure",
    examples: ["Minecraft-likes", "Necesse", "Minecraft Dungeons (dungeon-crawler take)"],
    dimension: "3d",
    coreLoop: "Punch world -> craft -> build home -> explore caves -> gear up -> boss dimension -> automation.",
    pillars: ["World is the toybox", "Crafting discovery", "Building pride", "Danger at depth"],
    keySystems: ["voxel chunk meshing", "block place/break", "crafting grids", "mobs & spawning rules", "cave/ore generation", "hunger & health", "day cycle"],
    mvpSlice: ["chunked voxel terrain", "break/place 6 block types", "craft table + 5 recipes", "2 mobs", "ore at depth", "save/load"],
    pitfalls: ["chunk meshing perf", "greedy meshing premature", "inventory UX"],
    engineFit: { godot4: 0.8, unreal5: 0.6 },
     config: {
      camera: "First-person with block-place raycast feedback",
      controls: "Mouse break/place; WASD; inventory hotbar",
      progression: "Discovery-driven; crafting milestones",
      content: "Seeded infinite chunks; structure tables",
      ui: "Hotbar, crafting book, map (late)",
      audio: "Block-step foley, ambient time-of-day",
      animation: "Arm swing sets; block pop VFX",
      save: "Region chunks + player state",
      performance: "Chunk mesh workers; 60fps on mid GPU",
      testing: "Chunk determinism, worldgen seams, save chunking",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "sports-arcade",
    label: "Sports / Arcade Competition",
    examples: ["eFootball", "Rocket League", "Golf With Your Friends"],
    dimension: "3d",
    coreLoop: "Match -> performance -> ranking/coins -> team building -> next match.",
    pillars: ["Match pacing", "Skill expression", "Fairness & anti-cheat", "Live-team content cadence"],
    keySystems: ["match rules & referee", "player/vehicle physics", "AI opponents difficulty bands", "ranking & matchmaking (later)", "team/collection meta", "replays"],
    mvpSlice: ["1 arena, 1v1 local", "core physics & scoring", "3-min matches", "1 AI difficulty", "scoreboard"],
    pitfalls: ["online infra scope", "meta exploits", "licensing (use fictional teams)"],
    engineFit: { godot4: 0.7, unreal5: 0.85 },
     config: {
      camera: "Broadcast follow; instant-replay angles",
      controls: "Contextual sport verbs; remappable; gamepad first",
      progression: "Season/career light; cosmetics",
      content: "Arena rulesets, team rosters (fictional)",
      ui: "Scoreboard, clock, replay overlay",
      audio: "Crowd dynamic layers, referee stingers",
      animation: "Sport motion sets; celebration moments",
      save: "Match records + settings",
      performance: "Physics parity for fairness; 60 lock",
      testing: "Rule engine integrity, physics parity, exploit soak",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "roguelite-action",
    label: "Roguelike / Roguelite Action",
    examples: ["Hades", "Dead Cells", "Risk of Rain", "Vampire Survivors"],
    dimension: "2d",
    coreLoop: "Enter a run of procedurally-arranged rooms -> fight encounters -> pick one of 2-3 upgrades -> build a synergy loadout -> die (or win) -> spend meta currency on permanent unlocks -> run again stronger.",
    pillars: ["Every death teaches something", "Build synergy discovery", "Runs are 20-40 min arcs", "Meta progression softens losses"],
    keySystems: ["room/chunk generation with encounter rules", "upgrade pool with rarity & tags", "build synergy validation", "meta-currency + unlock tree", "difficulty scaling", "death recap screen", "boss with pattern phases", "save/load of meta tree"],
    mvpSlice: ["3 biomes as room sets", "one playable character", "12 upgrades with real synergy", "meta unlock of 3 items", "run stats screen", "1 final boss"],
    pitfalls: ["upgrade pool with fake synergies", "room repetition before biome 2", "meta progression that invalidates the base game", "boss spike without counterplay telegraphs"],
    engineFit: { godot4: 0.85, unreal5: 0.4 },
    config: {
      camera: "2D follow with look-ahead; arena lock during encounters",
      controls: "Twin-stick or platformer movement + 2-3 action buttons; gamepad first-class",
      progression: "Intra-run upgrade choices + inter-run meta tree",
      content: "Chunk/room pools per biome, seeded run layout, elite/boss rooms",
      ui: "Pick-one upgrade overlay, loadout icons row, run timer, death recap",
      audio: "Layered music that intensifies with build power; hit-pitch scaling",
      animation: "Combat anticipation/impact frames, per-upgrade VFX tells",
      save: "Meta tree + unlocks; run state saved on quit-and-resume",
      performance: "60 fps with 100+ active projectiles/enemies; object pooling",
      testing: "Seeded run determinism tests, upgrade synergy unit tests, spawn soak",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
  {
    id: "tower-defense",
    label: "Tower Defense / Strategy Defense",
    examples: ["Kingdom Rush", "Dungeon Warfare", "They Are Billions (hybrid)"],
    dimension: "2.5d",
    coreLoop: "Inspect the incoming wave -> place/upgrade towers on the path -> start the wave -> read the leak -> adjust economy (towers vs interest) -> survive all waves or lose lives.",
    pillars: ["Legible counterplay (types vs types)", "Economy tension (build now vs save)", "Path & placement puzzle", "Escalating waves with gimmicks"],
    keySystems: ["wave spawner with scripted compositions", "tower types with counters (armor/flying/splash)", "targeting priorities", "economy (bounty + interest)", "lives & fail state", "tower upgrade tiers", "map path & buildable cells"],
    mvpSlice: ["one map with a fixed path", "4 tower types with real counters", "10 scripted waves + boss wave", "economy with interest", "win/lose screens"],
    pitfalls: ["one dominant tower strategy", "unreadable projectiles", "economy without tension", "wave pacing that never forces adaptation"],
    engineFit: { godot4: 0.85, unreal5: 0.4 },
    config: {
      camera: "Fixed isometric/angled board; zoom-out for wave overview",
      controls: "Mouse-driven (select/place/upgrade); hotkeys for speed & start",
      progression: "Level progression + per-run upgrade choices",
      content: "Maps as path graphs; wave scripts as data; boss/gimmick waves",
      ui: "Tower palette, range preview, wave preview bar, economy readout",
      audio: "Placement ticks, impact layering, danger stinger on leaks",
      animation: "Tower fire tells, projectile arcs, death pops",
      save: "Level unlocks & stars; mid-level resume",
      performance: "60 fps with 300 projectiles; deterministic simulation",
      testing: "Wave script parsing tests, counter table unit tests, leak-pathfinding checks",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
  {
    id: "factory-automation",
    label: "Building & Automation (Factory)",
    examples: ["Factorio", "Satisfactory", "Shapez", "Mindustry (hybrid)"],
    dimension: "2.5d",
    coreLoop: "Mine raw nodes -> hand-craft basics -> place machines & belts -> automate a part -> compound automation into the next part -> scale a self-running factory -> set a production goal and optimize it.",
    pillars: ["Every machine removes a chore", "Throughput as the visible score", "Bottleneck puzzles", "Expansion friction (distance, power, threats)"],
    keySystems: ["grid placement & deletion", "belt/pipe logistics with throughput", "machine recipes & crafting graph", "power system", "resource patches", "production stats panel", "blueprint copy-paste", "full-factory save/load"],
    mvpSlice: ["tile grid", "3 machines (miner/smelter/assembler)", "belts with real items", "one recipe chain (ore->plate->part)", "power via burner", "stats panel", "goal: produce 50 parts"],
    pitfalls: ["belt merge/split bugs (visual lies)", "recipes without a visible goal", "power blackouts that brick progress", "no throughput feedback = hidden bottlenecks"],
    engineFit: { godot4: 0.75, unreal5: 0.5 },
    config: {
      camera: "Free pan/zoom over the grid; click-to-focus on alerts",
      controls: "Mouse: place/rotate/delete; hotbars for machines; blueprint stamps",
      progression: "Tech tree gated by produced science/parts; milestone goals",
      content: "Seeded resource distribution; recipe graph as data; expansion areas",
      ui: "Toolbar, machine recipes card, power & throughput graphs, alerts",
      audio: "Machine hum layers that grow with the factory; satisfaction ticks",
      animation: "Item-on-belt motion, machine working states, smoke/VFX by load",
      save: "Full-factory serialization; autosave slots; crash-safe writes",
      performance: "Fixed simulation tick budget; chunked updates for 10k+ items",
      testing: "Recipe graph consistency tests, belt throughput sim tests, save roundtrip",
      platforms: ["windows", "linux", "macos"],
    },
  },
  {
    id: "deckbuilder",
    label: "Card & Deckbuilding Strategy",
    examples: ["Slay the Spire", "Monster Train", "Balatro"],
    dimension: "2d",
    coreLoop: "Build a deck from earned cards -> enter turn-based encounters -> play cards under energy constraints -> resolve telegraphed intents -> claim rewards (cards/relics) -> refine the deck against the final boss.",
    pillars: ["Every card changes the math visibly", "Deck as the character", "Intent-driven telegraphs", "Reward temptation vs deck coherence"],
    keySystems: ["card data (cost/type/effects)", "energy per turn", "draw/discard/resolve pipeline", "enemy intents telegraphed", "relics/passives", "deck view & pile counts", "encounter map", "run & meta save"],
    mvpSlice: ["20 starter cards", "3 enemies with distinct intents", "one boss with a pattern", "energy system", "reward picks after fights", "deck viewer", "win condition"],
    pitfalls: ["effects that don't stack consistently", "unreadable board state", "rewards that dilute decks without choice tension", "boss without counterplay to the starter deck"],
    engineFit: { godot4: 0.8, unreal5: 0.35 },
    config: {
      camera: "Static battle tableau; card hover inspect layer",
      controls: "Mouse drag/click to play; keyboard confirm/cancel & deck view",
      progression: "Run-based card rewards + ascension-style modifiers; meta unlocks",
      content: "Encounter tables, map nodes (fight/elite/shop/rest), card & relic pools",
      ui: "Hand fan, energy orb, intent icons, draw/discard piles, tooltips everywhere",
      audio: "Card play ticks, tension layering by boss phase; low-key explore music",
      animation: "Card draw/play arcs, number popups, intent flashes",
      save: "Mid-run save + meta unlocks",
      performance: "Trivial rendering; logic determinism matters (seeded shuffles)",
      testing: "Effect resolution unit tests (each card), RNG seed determinism, intent table checks",
      platforms: ["windows", "linux", "macos", "web"],
    },
  },
];

/** Keyword matcher: maps a free-form idea to the most relevant archetypes. */
export function matchArchetypes(text: string, limit = 3): GenreArchetype[] {
  const t = text.toLowerCase();
  const scored = GENRE_ARCHETYPES.map((a) => {
    let score = 0;
    for (const ex of a.examples) {
      const e = ex.toLowerCase().split(/[\s-]/)[0] ?? "";
      if (e.length > 3 && t.includes(e)) score += 3;
    }
    for (const s of a.keySystems) {
      const frag = s.toLowerCase().split(/[\s(/]/)[0] ?? "";
      if (frag.length > 4 && t.includes(frag)) score += 1;
    }
    if (t.includes(a.label.toLowerCase().split("/")[0]!.trim())) score += 4;
    return { a, score };
  });
  return scored.filter((s) => s.score > 0).sort((x, y) => y.score - x.score).slice(0, limit).map((s) => s.a);
}

export function archetypeContext(archetypes: GenreArchetype[]): string {
  return archetypes
    .map((a) =>
      `## ${a.label} (examples: ${a.examples.slice(0, 4).join(", ")})
Core loop: ${a.coreLoop}
Pillars: ${a.pillars.join(" | ")}
Key systems: ${a.keySystems.join(", ")}
MVP slice: ${a.mvpSlice.join(" -> ")}
Pitfalls to avoid: ${a.pitfalls.join("; ")}`
    )
    .join("\n\n");
}
